# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
  buildConfiguration: 'Release'
  springPetRepository: 'spring-petclinic'
  mySqlRepository: 'mysql'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'secret'
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: Cache@2
      displayName: Cache Maven local repo
      inputs:
        key: 'maven | "$(Agent.OS)" | **/pom.xml'
        restoreKeys: |
          maven | "$(Agent.OS)"
          maven
        path: $(MAVEN_CACHE_FOLDER)

    - script: mvn install -B -e
    - task: Maven@3
      displayName: 'Build the maven artifact'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: Docker@2
      displayName: 'Build and push the image to container registry'
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: $(springPetRepository)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: 'azure-container-registry'
        tags: |
          $(tag)
    
    - publish: '$(Build.SourcesDirectory)/manifests'
      artifact: manifests

- stage: Scan
  dependsOn: Build
  jobs:
  - job: Scan
    displayName: Scan with RHACS
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: Release
    steps:
    - script: |
        mkdir $(System.DefaultWorkingDirectory)/artifacts
        curl -k -L -H "Authorization: Bearer $ROX_API_TOKEN" https://$ROX_CENTRAL_ENDPOINT/api/cli/download/roxctl-linux --output ./roxctl
        chmod +x ./roxctl
        ./roxctl image scan --insecure-skip-tls-verify -e $ROX_CENTRAL_ENDPOINT --image $(ACR_RegistryName)/$(springPetRepository):$(tag) -o json > $(System.DefaultWorkingDirectory)/artifacts/image_scan.json
        ./roxctl image check --insecure-skip-tls-verify -e $ROX_CENTRAL_ENDPOINT --image $(ACR_RegistryName)/$(springPetRepository):$(tag)  > $(System.DefaultWorkingDirectory)/artifacts/image_check.txt
      displayName: 'RHACS image scan'
      env: 
        ROX_API_TOKEN: $(ACS_API_TOKEN)
        ROX_CENTRAL_ENDPOINT: '$(ACS_ENDPOINT)'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/artifacts'
        artifact: 'RHACS Output'
      

- stage: 'Deploy_Dev'
  displayName: 'Deploy to Dev'
  dependsOn: Scan
  condition: succeededOrFailed()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'openshift.dev'
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: manifests
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: 'azure-container-registry'
              kubernetesServiceConnection: 'openshift-dev-1652736334320'
              namespace: 'dev'
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: 'openshift-dev-1652736334320'
              namespace: 'dev'
              manifests: |
                $(Pipeline.Workspace)/manifests/dev/cm.yaml
                $(Pipeline.Workspace)/manifests/dev/secret.yaml
                $(Pipeline.Workspace)/manifests/dev/deployment.yaml
                $(Pipeline.Workspace)/manifests/dev/service.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(ACR_RegistryName)/$(springPetRepository):$(tag)
                $(ACR_RegistryName)/$(mySqlRepository):latest

- stage: 'Deploy_Stage'
  displayName: 'Deploy to Stage'
  dependsOn: Deploy_Dev
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'openshift.stage'
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: manifests
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: 'azure-container-registry'
              kubernetesServiceConnection: 'openshift-stage-1652464815216'
              namespace: 'stage'
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: 'openshift-stage-1652464815216'
              namespace: 'stage'
              manifests: |
                $(Pipeline.Workspace)/manifests/stage/cm.yaml
                $(Pipeline.Workspace)/manifests/stage/secret.yaml
                $(Pipeline.Workspace)/manifests/stage/deployment.yaml
                $(Pipeline.Workspace)/manifests/stage/service.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(ACR_RegistryName)/$(springPetRepository):$(tag)
                $(ACR_RegistryName)/$(mySqlRepository):latest
